title: Your Tutorial Hub
description: A collection of high-quality tutorials on cloud computing, DevOps, and more.
author: Your Name
url: "https://<your-username>.github.io"
baseurl: "/<repository-name>"

# Build settings
markdown: kramdown
theme: minima
plugins:
  - jekyll-feed
